version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: ./
    ports:
      - "8090:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
